<a href="https://colab.research.google.com/github/AndrewArnett/DS-Unit-2-Linear-Models/blob/master/U2_S1_M3_Assignment_DS_213_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 3*

---

# Ridge Regression

## Assignment

We're going back to our other **New York City** real estate dataset. Instead of predicting apartment rents, you'll predict property sales prices.

But not just for condos in Tribeca...

- [ ] Use a subset of the data where `BUILDING_CLASS_CATEGORY` == `'01 ONE FAMILY DWELLINGS'` and the sale price was more than 100 thousand and less than 2 million.
- [ ] Do train/test split. Use data from January — March 2019 to train. Use data from April 2019 to test.
- [ ] Do one-hot encoding of categorical features.
- [ ] Do feature selection with `SelectKBest`.
- [ ] Fit a ridge regression model with multiple features. Use the `normalize=True` parameter (or do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html) beforehand — use the scaler's `fit_transform` method with the train set, and the scaler's `transform` method with the test set)
- [ ] Get mean absolute error for the test set.
- [ ] As always, commit your notebook to your fork of the GitHub repo.

The [NYC Department of Finance](https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page) has a glossary of property sales terms and NYC Building Class Code Descriptions. The data comes from the [NYC OpenData](https://data.cityofnewyork.us/browse?q=NYC%20calendar%20sales) portal.


## Stretch Goals

Don't worry, you aren't expected to do all these stretch goals! These are just ideas to consider and choose from.

- [ ] Add your own stretch goal(s) !
- [ ] Instead of `Ridge`, try `LinearRegression`. Depending on how many features you select, your errors will probably blow up! 💥
- [ ] Instead of `Ridge`, try [`RidgeCV`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html).
- [ ] Learn more about feature selection:
    - ["Permutation importance"](https://www.kaggle.com/dansbecker/permutation-importance)
    - [scikit-learn's User Guide for Feature Selection](https://scikit-learn.org/stable/modules/feature_selection.html)
    - [mlxtend](http://rasbt.github.io/mlxtend/) library
    - scikit-learn-contrib libraries: [boruta_py](https://github.com/scikit-learn-contrib/boruta_py) & [stability-selection](https://github.com/scikit-learn-contrib/stability-selection)
    - [_Feature Engineering and Selection_](http://www.feat.engineering/) by Kuhn & Johnson.
- [ ] Try [statsmodels](https://www.statsmodels.org/stable/index.html) if you’re interested in more inferential statistical approach to linear regression and feature selection, looking at p values and 95% confidence intervals for the coefficients.
- [ ] Read [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf), Chapters 1-3, for more math & theory, but in an accessible, readable way.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [1]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [2]:
import pandas as pd
import pandas_profiling

# Read New York City property sales data
df = pd.read_csv(DATA_PATH+'condos/NYC_Citywide_Rolling_Calendar_Sales.csv')

# Change column names: replace spaces with underscores
df.columns = [col.replace(' ', '_') for col in df]

# SALE_PRICE was read as strings.
# Remove symbols, convert to integer
df['SALE_PRICE'] = (
    df['SALE_PRICE']
    .str.replace('$','')
    .str.replace('-','')
    .str.replace(',','')
    .astype(int)
)

In [3]:
# BOROUGH is a numeric column, but arguably should be a categorical feature,
# so convert it from a number to a string
df['BOROUGH'] = df['BOROUGH'].astype(str)

In [4]:
# Reduce cardinality for NEIGHBORHOOD feature

# Get a list of the top 10 neighborhoods
top10 = df['NEIGHBORHOOD'].value_counts()[:10].index

# At locations where the neighborhood is NOT in the top 10, 
# replace the neighborhood with 'OTHER'
df.loc[~df['NEIGHBORHOOD'].isin(top10), 'NEIGHBORHOOD'] = 'OTHER'

##EXPLORING AND FILTERING DATA

In [74]:
print(df.shape)
df.head()

(23040, 21)


BOROUGH             NEIGHBORHOOD  ... SALE_PRICE   SALE_DATE
0       1                    OTHER  ...          0  01/01/2019
1       1                    OTHER  ...          0  01/01/2019
2       1                    OTHER  ...          0  01/01/2019
3       1                    OTHER  ...          0  01/01/2019
4       1  UPPER EAST SIDE (59-79)  ...          0  01/01/2019

[5 rows x 21 columns]

In [75]:
subset = df[(df.BUILDING_CLASS_CATEGORY == '01 ONE FAMILY DWELLINGS')]

In [76]:
subset_1 = subset[(subset.SALE_PRICE > 100000)]

In [77]:
subset_2 = subset_1[(subset_1.SALE_PRICE < 2000000)]

In [78]:
print(subset_2.shape)
subset_2.head()

(3151, 21)


BOROUGH NEIGHBORHOOD  ... SALE_PRICE   SALE_DATE
44        3        OTHER  ...     550000  01/01/2019
61        4        OTHER  ...     200000  01/01/2019
78        2        OTHER  ...     810000  01/02/2019
108       3        OTHER  ...     125000  01/02/2019
111       3        OTHER  ...     620000  01/02/2019

[5 rows x 21 columns]

In [79]:
subset_2['SALE_DATE'] = pd.to_datetime(subset_2['SALE_DATE'], infer_datetime_format=True)
cutoff = pd.to_datetime('04/01/2019')
train = subset_2[subset_2.SALE_DATE < cutoff]
test = subset_2[subset_2.SALE_DATE >= cutoff]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [80]:
print(train.shape)
print(test.shape)

(2507, 21)
(644, 21)


##TRAIN/TEST DATA

In [81]:
X_train = train.drop('SALE_PRICE', axis=1)
y_train =train['SALE_PRICE']

X_test = test.drop('SALE_PRICE', axis=1)
y_test = test['SALE_PRICE']

##ONE HOT ENCODING

In [82]:
subset_2['NEIGHBORHOOD'].value_counts()

OTHER                 2959
FLUSHING-NORTH          97
EAST NEW YORK           31
FOREST HILLS            22
BOROUGH PARK            19
ASTORIA                 14
BEDFORD STUYVESANT       9
Name: NEIGHBORHOOD, dtype: int64

In [83]:
subset_2['BOROUGH'].value_counts()

4    1580
5     738
3     537
2     293
1       3
Name: BOROUGH, dtype: int64

In [90]:
subset_2['APARTMENT_NUMBER'].value_counts()

RP.    1
Name: APARTMENT_NUMBER, dtype: int64

In [85]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)

ohe.fit(train[['NEIGHBORHOOD']])

train_trans = ohe.transform(train[['NEIGHBORHOOD']])

In [86]:
train_trans

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [87]:
ohe.fit(train[['BOROUGH']])

train_trans_borough = ohe.transform(train[['BOROUGH']])

In [88]:
train_trans_borough

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

##SelectKBest

In [91]:
X_train = X_train.select_dtypes(include='number')
X_test = X_test.select_dtypes(include='number')

X_train = X_train.drop('EASE-MENT', axis=1)
X_test = X_test.drop('EASE-MENT', axis=1)

In [93]:
X_train.shape

(2507, 9)

In [94]:
from sklearn.feature_selection import SelectKBest
selector = SelectKBest(k=5)
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning: Features [8] are constant.
  UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [95]:
X_test_selected

array([[1.000e+00, 0.000e+00, 1.000e+00, 2.272e+03, 1.930e+03],
       [1.000e+00, 0.000e+00, 1.000e+00, 7.200e+02, 1.935e+03],
       [1.000e+00, 0.000e+00, 1.000e+00, 2.210e+03, 1.925e+03],
       ...,
       [1.000e+00, 0.000e+00, 1.000e+00, 1.333e+03, 1.945e+03],
       [1.000e+00, 0.000e+00, 1.000e+00, 1.020e+03, 1.935e+03],
       [1.000e+00, 0.000e+00, 1.000e+00, 1.224e+03, 1.945e+03]])

##RIDGE REGRESSION

In [96]:
from sklearn.linear_model import Ridge

In [98]:
ridge = Ridge(alpha=5, normalize=True)
ridge.fit(X_train, y_train)

Ridge(alpha=5, copy_X=True, fit_intercept=True, max_iter=None, normalize=True,
      random_state=None, solver='auto', tol=0.001)

In [99]:
ridge.coef_

array([-1.93668628e+00, -1.22450606e+01,  2.21594331e+01,  2.34275006e+04,
        3.54249616e+04,  2.99728082e+04,  3.60198005e+01, -6.04849807e+01,
        0.00000000e+00])

In [100]:
ridge.intercept_

402718.54821008246

##MAE

In [103]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
lr = LinearRegression()

In [105]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [106]:
print('Training MAE:', mean_absolute_error(y_train, lr.predict(X_train)))
print('Testing MAE:', mean_absolute_error(y_test, lr.predict(X_test)))

Training MAE: 166969.32246640217
Testing MAE: 167704.58795917808
