<a href="https://colab.research.google.com/github/Data-alchemist-mani/DS-Unit-2-Linear-Models/blob/master/module2-regression-2/Copy_of_LS_DS_212_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 2*

---

# Regression 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [ ] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [ ] Engineer at least two new features. (See below for explanation & ideas.)
- [ ] Fit a linear regression model with at least two features.
- [ ] Get the model's coefficients and intercept.
- [ ] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [ ] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [ ] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [ ] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Add your own stretch goal(s) !

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import numpy as np
import pandas as pd

# Read New York City apartment rental listing data
df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [199]:
df.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [0]:
df['created'] = pd.to_datetime(df['created'])

In [201]:
df.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [0]:
df['Months'] = df['created'].dt.month

In [203]:
df.head()

bathrooms  bedrooms  ... common_outdoor_space Months
0        1.5         3  ...                    0      6
1        1.0         2  ...                    0      6
2        1.0         1  ...                    0      4
3        1.0         1  ...                    0      4
4        1.0         4  ...                    0      4

[5 rows x 35 columns]

In [204]:
train.shape, test.shape

((31844, 36), (16973, 36))

In [205]:
df.columns

Index(['bathrooms', 'bedrooms', 'created', 'description', 'display_address',
       'latitude', 'longitude', 'price', 'street_address', 'interest_level',
       'elevator', 'cats_allowed', 'hardwood_floors', 'dogs_allowed',
       'doorman', 'dishwasher', 'no_fee', 'laundry_in_building',
       'fitness_center', 'pre-war', 'laundry_in_unit', 'roof_deck',
       'outdoor_space', 'dining_room', 'high_speed_internet', 'balcony',
       'swimming_pool', 'new_construction', 'terrace', 'exclusive', 'loft',
       'garden_patio', 'wheelchair_access', 'common_outdoor_space', 'Months'],
      dtype='object')

In [0]:
df['interest_level'] = df['interest_level'].map({'high': 3, 'medium': 2, 'low': 1})

In [207]:
df.head()

bathrooms  bedrooms  ... common_outdoor_space Months
0        1.5         3  ...                    0      6
1        1.0         2  ...                    0      6
2        1.0         1  ...                    0      4
3        1.0         1  ...                    0      4
4        1.0         4  ...                    0      4

[5 rows x 35 columns]

In [0]:
df['feature_counts'] = (df['elevator']+
                       df['cats_allowed']+
                       df['hardwood_floors']+
                       df['dogs_allowed']+
                       df['doorman']+
                       df['dishwasher']+
                       df['no_fee']+
                       df['laundry_in_building']+
                       df['fitness_center']+
                       df['pre-war']+
                       df['laundry_in_unit']+
                       df['roof_deck']+
                       df['outdoor_space']+
                       df['dining_room']+
                       df['high_speed_internet']+
                       df['balcony']+df['swimming_pool']+
                       df['new_construction']+
                       df['terrace']+
                       df['exclusive']+
                       df['loft']+
                       df['garden_patio']+
                       df['wheelchair_access']+
                       df['common_outdoor_space'])

In [209]:
df.head()

bathrooms  bedrooms  ... Months feature_counts
0        1.5         3  ...      6              0
1        1.0         2  ...      6              5
2        1.0         1  ...      4              3
3        1.0         1  ...      4              2
4        1.0         4  ...      4              1

[5 rows x 36 columns]

In [0]:
import plotly.express as px

In [211]:
px.scatter_3d(train,
              x='interest_level',
              y='feature_counts',
              z='price')

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
model = LinearRegression()

In [213]:
train['Months'].value_counts()

4    16217
5    15627
Name: Months, dtype: int64

In [214]:
test['Months'].value_counts()

6    16973
Name: Months, dtype: int64

In [0]:
train = df[df['Months'] <= 5 ]

In [0]:
test = df[df['Months'] > 5 ]

In [0]:
target = 'price'
y_train = train[target]
y_test = test[target]

In [0]:
features = ['feature_counts', 'interest_level']

X_train = train[features]
X_test = test[features]

In [219]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
y_pred = model.predict(X_train)

In [221]:
y_train

2        2850
3        3275
4        3350
5        7995
6        3600
         ... 
49346    4500
49348    3950
49349    2595
49350    3350
49351    2200
Name: price, Length: 31844, dtype: int64

In [222]:
y_pred

array([2324.18538312, 3376.24576218, 3217.0421471 , ..., 3853.85660742,
       3853.85660742, 3217.0421471 ])

In [223]:
(y_pred - y_train).abs().mean()

1106.4960237797536

In [224]:
mae = mean_absolute_error
print(f'Train error: ${mae(y_pred, y_train)}')

Train error: $1106.496023779732


In [225]:
y_pred = model.predict(X_test)
print(f'Test error: ${mae(y_test, y_pred)}')

Test error: $1095.8932371127123


In [0]:
import itertools
import numpy as np
import plotly.express as px
import plotly.graph_objs as go
from sklearn.linear_model import LinearRegression

def regression_3d(df, x, y, z, num=100, **kwargs):
    """
    Visualize linear regression in 3D: 2 features + 1 target
    
    df : Pandas DataFrame
    x : string, feature 1 column in df
    y : string, feature 2 column in df
    z : string, target column in df
    num : integer, number of quantiles for each feature
    """
    
    # Plot data
    fig = px.scatter_3d(df, x, y, z, **kwargs)
    
    # Fit Linear Regression
    features = [x, y]
    target = z
    model = LinearRegression()
    model.fit(df[features], df[target])    
    
    # Define grid of coordinates in the feature space
    xmin, xmax = df[x].min(), df[x].max()
    ymin, ymax = df[y].min(), df[y].max()
    xcoords = np.linspace(xmin, xmax, num)
    ycoords = np.linspace(ymin, ymax, num)
    coords = list(itertools.product(xcoords, ycoords))
    
    # Make predictions for the grid
    predictions = model.predict(coords)
    Z = predictions.reshape(num, num).T
    
    # Plot predictions as a 3D surface (plane)
    fig.add_trace(go.Surface(x=xcoords, y=ycoords, z=Z))
    
    return fig

In [227]:
regression_3d(train,
              x='interest_level',
              y='feature_counts',
              z='price')

In [228]:
model.intercept_

3663.4705290828

In [229]:
model.coef_

array([ 159.20361508, -605.63199707])

In [232]:
beta0 = model.intercept_
beta1, beta2 = model.coef_
print(f'y = {beta0} + {beta1}x1 + {beta2}x2')

y = 3663.4705290828 + 159.20361508231076x1 + -605.631997069531x2


In [230]:
print(f'intercept: {model.intercept_}')
coeficients = pd.Series(model.coef_, features)
print(coeficients.to_string())

intercept: 3663.4705290828
feature_counts    159.203615
interest_level   -605.631997


In [235]:
#featt
model.predict([[7, 1]])

array([4172.26383759])