Lambda School Data Science

*Unit 2, Sprint 1, Module 2*

---

# Regression 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [X] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [X] Engineer at least two new features. (See below for explanation & ideas.)
- [X] Fit a linear regression model with at least two features.
- [X] Get the model's coefficients and intercept.
- [X] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [ ] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [ ] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [ ] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Add your own stretch goal(s) !

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import numpy as np
import pandas as pd

# Read New York City apartment rental listing data
df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [20]:
df.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [6]:
df.created.isnull().any()

False

In [10]:
df.dtypes

bathrooms               float64
bedrooms                  int64
created                  object
description              object
display_address          object
latitude                float64
longitude               float64
price                     int64
street_address           object
interest_level           object
elevator                  int64
cats_allowed              int64
hardwood_floors           int64
dogs_allowed              int64
doorman                   int64
dishwasher                int64
no_fee                    int64
laundry_in_building       int64
fitness_center            int64
pre-war                   int64
laundry_in_unit           int64
roof_deck                 int64
outdoor_space             int64
dining_room               int64
high_speed_internet       int64
balcony                   int64
swimming_pool             int64
new_construction          int64
terrace                   int64
exclusive                 int64
loft                      int64
garden_p

In [24]:
train = df[df.created < '2016-06-01']
train.sort_values(by='created')

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
5186         1.0         1  ...                 0                    0
7945         1.0         0  ...                 0                    0
6424         2.0         3  ...                 0                    1
7719         1.0         1  ...                 0                    1
1723         1.0         1  ...                 0                    0
...          ...       ...  ...               ...                  ...
15311        1.0         4  ...                 0                    0
20331        1.0         2  ...                 0                    0
35264        1.0         2  ...                 0                    0
22002        1.0         2  ...                 0                    0
15697        1.0         1  ...                 0                    0

[31844 rows x 34 columns]

In [25]:
test = df[df.created >= '2016-06-01']
test.sort_values(by='created')

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
11474        1.0         1  ...                 0                    0
19176        1.0         1  ...                 0                    0
16226        1.0         2  ...                 0                    0
37756        1.0         0  ...                 0                    0
17946        1.0         2  ...                 0                    0
...          ...       ...  ...               ...                  ...
19943        1.0         2  ...                 0                    0
16801        1.0         1  ...                 0                    0
32633        1.0         1  ...                 0                    0
20560        1.0         3  ...                 0                    0
17743        1.0         3  ...                 0                    0

[16973 rows x 34 columns]

(40.7727, -73.9931), (40.7586, -73.9597)

40.7727 - 40.7586 = 0.0141
-73.9931 - -73.9597 = -0.0334

(40.767827, -73.981174), (40.764427, -73.973244)
0.0034 / .00793 = .42875


-0.0334 / 0.0141 = -2.36879

40.7727 * -2.36879 = -96.581964

-96.581964 - -73.9931 = -22.588864

y = (-2.36879)x + 22.588864

-2.36879 * 40.7586 + 22.588864 = -73.9597001

In [0]:
def equation_south(row):
    distance = (df.latitude[row] * (-.42215)) + 91.179029 + df.longitude[row]
    if distance > 0:
        return distance
    else: 
        return 0

In [172]:
equation_south(0)

0.048902824999998984

In [0]:
def equation_west(row):
    distance = (df.latitude[row] * (2.368)) - 22.642040 + df.longitude[row]
    if distance > 0:
        return distance
    else:
        return 0

In [174]:
equation_west(0)

0

In [0]:
def equation_north(row):
    distance = ((df.latitude[row] * (-.42215)) + 91.190692 + df.longitude[row])*(-1)
    if distance > 0:
        return distance
    else:
        return 0

In [176]:
equation_north(0)

0

In [0]:
def equation_east(row):
    distance = ((df.latitude[row] * (2.368)) - 22.643960 + df.longitude[row])*(-1)
    if distance > 0:
        return distance
    else:
        return 0

In [178]:
equation_east(0)

0.17452399999999102

In [0]:
train['distance_to_59th_street'] = abs((train['latitude'] * (-2.36879)) + 22.588864 - train['longitude'])
test['distance_to_59th_street'] = abs((test['latitude'] * (-2.36879)) + 22.588864 - test['longitude'])

In [95]:
test.head()

bathrooms  bedrooms  ... modern rooms
0         1.5         3  ...  False   4.5
1         1.0         2  ...  False   3.0
11        1.0         1  ...  False   2.0
14        1.0         1  ...  False   2.0
24        2.0         4  ...  False   6.0

[5 rows x 37 columns]

In [0]:
train['modern'] = ((train['new_construction'] == 1) & (train['high_speed_internet'] == 1)
                & (train['dishwasher'] == 1) & (train['fitness_center'] == 1))

test['modern'] = ((test['new_construction'] == 1) & (test['high_speed_internet'] == 1)
                & (test['dishwasher'] == 1) & (test['fitness_center'] == 1))

In [0]:
train['rooms'] = train['bathrooms'] + train['bedrooms']

test['rooms'] = test['bathrooms'] + test['bedrooms']

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

model = LinearRegression()

features = ['modern', 'rooms', 'distance_to_59th_street']
target = 'price'

X_train = train[features]
X_test = test[features]

y_train = train[target]
y_test = test[target]

In [91]:
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)

y_pred_train

array([2946.02685449, 3267.18030929, 5056.36570816, ..., 3232.18464663,
       1736.53518538, 2768.65683704])

In [92]:
mean_absolute_error(y_train, y_pred_train)

871.7972302552689

In [93]:
y_pred_test = model.predict(X_test)

y_pred_test

array([5005.86816291, 3814.97795941, 2324.17271294, ..., 3298.41035046,
       3821.5565539 , 3912.94311444])

In [94]:
mean_absolute_error(y_test, y_pred_test)

881.9882058539434

In [114]:
model.intercept_

1713.6461002640378

In [115]:
model.coef_

array([  450.58524844,   820.74027728, -4596.52636302])

In [127]:
mse_train = mean_squared_error(y_train, y_pred_train)
mse_train

1692435.1009012675

In [126]:
mse_test = mean_squared_error(y_test, y_pred_test)
mse_test

1682640.9402935356

In [121]:
import numpy as np

rmse_train = np.sqrt(mse_train)
rmse_train 

1300.9362401367976

In [123]:
rmse_test = np.sqrt(mse_test)
rmse_test

1297.166504460216

In [124]:
r_2_train = r2_score(y_train, y_pred_train)
r_2_train

0.45493728812207934

In [125]:
r_2_test = r2_score(y_test, y_pred_test)
r_2_test

0.4586134407451692