<a href="https://colab.research.google.com/github/dougscohen/DS-Unit-2-Linear-Models/blob/master/module2-regression-2/LS_DS_212_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 2*

---

# Regression 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [ ] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [ ] Engineer at least two new features. (See below for explanation & ideas.)
- [ ] Fit a linear regression model with at least two features.
- [ ] Get the model's coefficients and intercept.
- [ ] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [ ] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [ ] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [ ] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Add your own stretch goal(s) !

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import numpy as np
import pandas as pd

# Read New York City apartment rental listing data
df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [163]:
# view first 5 rows of the dataset

df.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [164]:
# Feature Engineering Part 1

# Create 'total rooms' column that adds the numbers of bedrooms and bathrooms
# together

df['total_rooms'] = df['bedrooms'] + df['bathrooms']

df.head()

bathrooms  bedrooms  ... common_outdoor_space total_rooms
0        1.5         3  ...                    0         4.5
1        1.0         2  ...                    0         3.0
2        1.0         1  ...                    0         2.0
3        1.0         1  ...                    0         2.0
4        1.0         4  ...                    0         5.0

[5 rows x 35 columns]

In [165]:
# Feature Engineering Part 1

# Create 'total perks' column that counts up the total number of perks each
# observation has

df['total_perks'] = (df['elevator'] +
                     df['hardwood_floors'] +
                     df['doorman'] +
                     df['dishwasher'] +
                     df['no_fee'] +
                     df['laundry_in_building'] +
                     df['fitness_center'] +
                     df['laundry_in_unit'] +
                     df['roof_deck'] +
                     df['outdoor_space'] +
                     df['dining_room'] +
                     df['high_speed_internet'] +
                     df['balcony'] +
                     df['swimming_pool'] +
                     df['terrace'] +
                     df['loft'] +
                     df['garden_patio'] +
                     df['wheelchair_access'] +
                     df['common_outdoor_space'])

df.head()

bathrooms  bedrooms  ... total_rooms total_perks
0        1.5         3  ...         4.5           0
1        1.0         2  ...         3.0           3
2        1.0         1  ...         2.0           3
3        1.0         1  ...         2.0           2
4        1.0         4  ...         5.0           0

[5 rows x 36 columns]

In [166]:
# See the data types of the features (I specifically care about the 'created'
# column)

df.dtypes.head()

bathrooms          float64
bedrooms             int64
created             object
description         object
display_address     object
dtype: object

In [167]:
import pandas as pd

# Turn 'created' column into datetime format so that later we can split the
# dataset based on month

df['created'] = pd.to_datetime(df['created'], infer_datetime_format=True)

# Ensure the column is now a datetime datatype

df.dtypes.head()

bathrooms                 float64
bedrooms                    int64
created            datetime64[ns]
description                object
display_address            object
dtype: object

In [168]:
# Create a new column in our dataframe that shows just the month in 'created'

df['created_month'] = df['created'].dt.month

df.head()

bathrooms  bedrooms  ... total_perks created_month
0        1.5         3  ...           0             6
1        1.0         2  ...           3             6
2        1.0         1  ...           3             4
3        1.0         1  ...           2             4
4        1.0         4  ...           0             4

[5 rows x 37 columns]

In [169]:
# check out the different values in the month column

df['created_month'].value_counts()

6    16973
4    16217
5    15627
Name: created_month, dtype: int64

In [170]:
# Split the dataframe into test and train subsets based on month

train = df[df['created_month'] < 6]
test = df[df['created_month'] >= 6]

train.shape, test.shape

((31844, 37), (16973, 37))

In [171]:
# Evaluate the first 5 rows of the train subset

train.head()

bathrooms  bedrooms  ... total_perks created_month
2        1.0         1  ...           3             4
3        1.0         1  ...           2             4
4        1.0         4  ...           0             4
5        2.0         4  ...           0             4
6        1.0         2  ...           1             4

[5 rows x 37 columns]

In [0]:
# 1. Import Estimator

from sklearn.linear_model import LinearRegression

In [0]:
# 2. Instantiate the class

model = LinearRegression()

In [174]:
# 3. Arrange X features matrix and y target vector

features = ['total_rooms', 'total_perks']
target = ['price']

X_train = train[features]
X_test = test[features]
y_train = train[target]
y_test = test[target]

print(f'Linear Regression, dependent on: {features}')

Linear Regression, dependent on: ['total_rooms', 'total_perks']


In [175]:
# 4. Fit the model

model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [176]:
# Fine the coefficients of each feature

model.coef_

array([[764.5053396, 110.4029258]])

In [177]:
# Fine the y-intercept

model.intercept_

array([1099.71700945])

In [178]:
# 5a. Apply the model to the train data

y_pred = model.predict(X_train)
y_pred

array([[2959.93646605],
       [2849.53354025],
       [4922.24370743],
       ...,
       [2849.53354025],
       [2085.02820065],
       [3503.63595404]])

In [179]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Training MAE
train_mae = mean_absolute_error(y_train, y_pred)

# Training MSE & RMSE
train_mse = mean_squared_error(y_train, y_pred)
train_rmse = np.sqrt(train_mse)

# Training R2 score
train_r2 = r2_score(y_train, y_pred)

print(train_mae)
print(train_rmse)
print(train_r2)

857.7186096277825
1296.1324350592124
0.4589552263864911


In [180]:
# 5b. Apply the model to the test data

y_pred = model.predict(X_test)
y_pred

array([[4539.99103763],
       [3724.44180564],
       [2628.72768864],
       ...,
       [2628.72768864],
       [3503.63595404],
       [3945.24765725]])

In [181]:
# Testing MAE
test_mae = mean_absolute_error(y_test, y_pred)

# Testing MSE & RMSE
test_mse = mean_squared_error(y_test, y_pred)
test_rmse = np.sqrt(test_mse)

# Training R2 score
test_r2 = r2_score(y_test, y_pred)

print(test_mae)
print(test_rmse)
print(test_r2)

869.2177059963768
1294.424656734037
0.46089970191268537
