Lambda School Data Science

*Unit 2, Sprint 1, Module 4*

---

# Logistic Regression


## Assignment 🌯

You'll use a [**dataset of 400+ burrito reviews**](https://srcole.github.io/100burritos/). How accurately can you predict whether a burrito is rated 'Great'?

> We have developed a 10-dimensional system for rating the burritos in San Diego. ... Generate models for what makes a burrito great and investigate correlations in its dimensions.

- [ ] Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your model's validation accuracy. (Multiple times if you try multiple iterations.)
- [ ] Get your model's test accuracy. (One time, at the end.)
- [ ] Commit your notebook to your fork of the GitHub repo.


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Linear-Models/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [0]:
# Load data downloaded from https://srcole.github.io/100burritos/
import pandas as pd
df = pd.read_csv(DATA_PATH+'burritos/burritos.csv')

In [0]:
# Derive binary classification target:
# We define a 'Great' burrito as having an
# overall rating of 4 or higher, on a 5 point scale.
# Drop unrated burritos.
df = df.dropna(subset=['overall'])
df['Great'] = df['overall'] >= 4

In [0]:
# Clean/combine the Burrito categories
df['Burrito'] = df['Burrito'].str.lower()

california = df['Burrito'].str.contains('california')
asada = df['Burrito'].str.contains('asada')
surf = df['Burrito'].str.contains('surf')
carnitas = df['Burrito'].str.contains('carnitas')

df.loc[california, 'Burrito'] = 'California'
df.loc[asada, 'Burrito'] = 'Asada'
df.loc[surf, 'Burrito'] = 'Surf & Turf'
df.loc[carnitas, 'Burrito'] = 'Carnitas'
df.loc[~california & ~asada & ~surf & ~carnitas, 'Burrito'] = 'Other'

In [0]:
# Drop some high cardinality categoricals
df = df.drop(columns=['Notes', 'Location', 'Reviewer', 'Address', 'URL', 'Neighborhood'])

In [0]:
# Drop some columns to prevent "leakage"
df = df.drop(columns=['Rec', 'overall'])

In [8]:
df.head()

Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California  1/18/2016   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California  1/24/2016   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada  1/24/2016   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California  1/27/2016   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 59 columns]

In [0]:
#one hot encode

#Do train/validate/test split. Train on reviews from 2016 & earlier. Validate on 2017. Test on 2018 & later.

In [0]:
df['Date'] = pd.to_datetime(df['Date'])

In [11]:
df['Date'].tail()

418   2019-08-27
419   2019-08-27
420   2019-08-27
421   2019-08-27
422   2019-08-27
Name: Date, dtype: datetime64[ns]

In [12]:
df['Date'].dt.year

0      2016
1      2016
2      2016
3      2016
4      2016
       ... 
418    2019
419    2019
420    2019
421    2019
422    2019
Name: Date, Length: 421, dtype: int64

In [13]:
#create test DataFrame
condition_test = df['Date'].dt.year >= 2018
df_test = df[condition_test]
df_test.head(5)

Burrito       Date  Yelp  Google  ... Avocado  Corn  Zucchini  Great
77   California 2026-04-25   NaN     NaN  ...     NaN   NaN       NaN   True
386  California 2018-01-02   NaN     NaN  ...     NaN   NaN       NaN  False
387       Other 2018-01-09   4.5     3.8  ...     NaN   NaN       NaN  False
388  California 2018-01-12   3.5     4.3  ...     NaN   NaN       NaN   True
389       Other 2018-01-12   NaN     NaN  ...     NaN   NaN       NaN  False

[5 rows x 59 columns]

In [14]:
#replace False with 0 and True with 1
df_test['Great'] = df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [15]:
df_test.shape

(38, 59)

In [16]:
#create train 
condition_train = df['Date'].dt.year <= 2016
df_train = df[condition_train]
df_train.head()

Burrito       Date  Yelp  Google Chips  ...  Sushi  Avocado  Corn  Zucchini  Great
0  California 2016-01-18   3.5     4.2   NaN  ...    NaN      NaN   NaN       NaN  False
1  California 2016-01-24   3.5     3.3   NaN  ...    NaN      NaN   NaN       NaN  False
2    Carnitas 2016-01-24   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
3       Asada 2016-01-24   NaN     NaN   NaN  ...    NaN      NaN   NaN       NaN  False
4  California 2016-01-27   4.0     3.8     x  ...    NaN      NaN   NaN       NaN   True

[5 rows x 59 columns]

In [17]:
df_train.shape

(298, 59)

In [18]:
#validate DataFrame
condition_val = df['Date'].dt.year == 2017
df_val = df[condition_val]
df_val.head()

Burrito       Date  Yelp  Google  ... Avocado  Corn  Zucchini  Great
301  California 2017-01-04   NaN     NaN  ...     NaN   NaN       NaN  False
302       Other 2017-01-04   NaN     NaN  ...     NaN   NaN       NaN  False
303       Other 2017-01-07   NaN     NaN  ...     NaN   NaN       NaN  False
304       Other 2017-01-07   NaN     NaN  ...     NaN   NaN       NaN  False
305       Other 2017-01-10   NaN     NaN  ...     NaN   NaN       NaN  False

[5 rows x 59 columns]

In [19]:
df_val.shape

(85, 59)

#Begin with baselines for classification.

In [49]:
#determine the majority class
target = "Great"
y_train = df_train[target]
y_train.value_counts(normalize=True)

False    0.590604
True     0.409396
Name: Great, dtype: float64

In [55]:
#What if we guessed the majority class for every prediction?
majority_class = y_train.mode()[0] #mode() gets the most frequent on in the array
y_train.mode()[0]

False

In [22]:
y_train.head()

0    False
1    False
2    False
3    False
4     True
Name: Great, dtype: bool

In [0]:
y_pred_train = [majority_class]*len(y_train)

In [25]:
y_pred_train[:5]

[False, False, False, False, False]

In [26]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_pred_train)

0.5906040268456376

In [27]:
#validation
y_val = df_val[target]
y_pred = [majority_class]*len(y_val)

accuracy_score(y_val, y_pred)

0.5529411764705883

#Use scikit-learn for linear regression.

In [28]:
df_train.describe(include='all')

Burrito                 Date       Yelp  ...  Corn Zucchini  Great
count          298                  298  71.000000  ...     2        1    298
unique           5                  110        NaN  ...     2        1      2
top     California  2016-08-30 00:00:00        NaN  ...     X        x  False
freq           118                   29        NaN  ...     1        1    176
first          NaN  2011-05-16 00:00:00        NaN  ...   NaN      NaN    NaN
last           NaN  2016-12-15 00:00:00        NaN  ...   NaN      NaN    NaN
mean           NaN                  NaN   3.897183  ...   NaN      NaN    NaN
std            NaN                  NaN   0.478680  ...   NaN      NaN    NaN
min            NaN                  NaN   2.500000  ...   NaN      NaN    NaN
25%            NaN                  NaN   3.500000  ...   NaN      NaN    NaN
50%            NaN                  NaN   4.000000  ...   NaN      NaN    NaN
75%            NaN                  NaN   4.000000  ...   NaN      NaN    NaN
max            NaN                  NaN   4.500000  ...   NaN      NaN    NaN

[13 rows x 59 columns]

In [29]:
df.isnull().sum()

Burrito             0
Date                0
Yelp              334
Google            334
Chips             395
Cost                7
Hunger              3
Mass (g)          399
Density (g/mL)    399
Length            138
Circum            140
Volume            140
Tortilla            0
Temp               20
Meat               14
Fillings            3
Meat:filling        9
Uniformity          2
Salsa              25
Synergy             2
Wrap                3
Unreliable        388
NonSD             414
Beef              242
Pico              263
Guac              267
Cheese            262
Fries             294
Sour cream        329
Pork              370
Chicken           400
Shrimp            400
Fish              415
Rice              385
Beans             386
Lettuce           410
Tomato            414
Bell peper        414
Carrots           420
Cabbage           413
Sauce             383
Salsa.1           414
Cilantro          406
Onion             404
Taquito           417
Pineapple 

In [30]:
#1. import estimator class
from sklearn.linear_model import LinearRegression

#2. instantiate the class
linear_reg = LinearRegression()

#3. Arrange X feature matrices
features = ['Yelp', 'Google', 'Cost']
X_train = df_train[features]
X_val = df_val[features]

#impute missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.fit_transform(X_val)

#4 fit the model
linear_reg.fit(X_train_imputed, y_train)

#5. apply mmodel to new data
linear_reg.predict(X_val_imputed)

array([0.40063976, 0.40063976, 0.51000577, 0.47546913, 0.30796647,
       0.3965123 , 0.47489352, 0.4518691 , 0.4518691 , 0.47546913,
       0.47546913, 0.36552752, 0.42308857, 0.41503003, 0.41503003,
       0.45716609, 0.43160468, 0.47546913, 0.47546913, 0.47546913,
       0.47546913, 0.4952915 , 0.3862495 , 0.45244471, 0.39488366,
       0.39488366, 0.29415181, 0.40927392, 0.39488366, 0.40927392,
       0.43420662, 0.4956155 , 0.36552752, 0.36552752, 0.59634735,
       0.59634735, 0.20241108, 0.38049339, 0.50275105, 0.46683498,
       0.65020443, 0.53821068, 0.41503003, 0.41503003, 0.44668861,
       0.44668861, 0.5934693 , 0.43623295, 0.53878629, 0.42366419,
       0.42308857, 0.43460079, 0.47489352, 0.47489352, 0.41790808,
       0.51288382, 0.46971303, 0.28914924, 0.34077627, 0.34077627,
       0.39315683, 0.58283461, 0.42308857, 0.42308857, 0.51000577,
       0.51000577, 0.40927392, 0.47546913, 0.50137161, 0.2965351 ,
       1.45976316, 0.42366419, 0.43565734, 0.42942029, 0.39315

In [31]:
#get the coefficients
pd.Series(linear_reg.coef_, features)

Yelp      0.159521
Google    0.077824
Cost      0.057561
dtype: float64

In [32]:
test_case = [[3.5,4.2,6.49]]
linear_reg.predict(test_case)

array([0.32711614])

In [45]:
#This is why you should not use linear regression for this model, 
#or even the column price without standarizing 
test_case2 = [[5,5,20]]
linear_reg.predict(test_case2)

array([1.40630748])

#Use scikit-learn for logistic regression (this is used for classification not regression (I know confusing)

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_reg = LogisticRegression()
log_reg.fit(X_train_imputed, y_train)
print("Validation Accuracy", log_reg.score(X_val_imputed, y_val))


Validation Accuracy 0.5058823529411764


In [59]:
#samething as above
y_pred = log_reg.predict(X_val_imputed)
print("Accuracy score", accuracy_score(y_pred, y_val))


Accuracy score 0.5058823529411764


In [60]:
#the prediction looks like this
y_pred

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False,  True,  True, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False,  True,  True, False, False,  True, False,  True, False,
       False, False, False,  True, False, False,  True,  True, False,
       False,  True, False, False])

In [61]:
#testing the same test cases from linear regression above
log_reg.predict(test_case)

array([False])

In [62]:
log_reg.predict(test_case2)

array([ True])

In [65]:
#predicts the probabilities and returns array with 
#number of index according to the classes (here 2 for True and False)
log_reg.predict_proba(test_case)

array([[0.66384102, 0.33615898]])

In [66]:
log_reg.predict_proba(test_case2)

array([[0.02454732, 0.97545268]])

In [67]:
log_reg.coef_

array([[0.56654209, 0.31286743, 0.24149892]])

In [68]:
log_reg.intercept_

array([-5.54472701])

In [0]:
#sigmoid only outputs values between 0 and 1 
#which is good for logistic regression 
import numpy as np
def sigmoid(x):
  return 1/(1 + np.e**(-x))

In [70]:
#behind the scenes of the predict_proba method
sigmoid(log_reg.intercept_ + np.dot(log_reg.coef_, np.transpose(test_case)))

array([[0.33615898]])

#Get your model's validation accuracy. (Multiple times if you try multiple iterations.)

In [72]:
print("Validation Accuracy", log_reg.score(X_val_imputed, y_val))

Validation Accuracy 0.5058823529411764


#Get your model's test accuracy. (One time, at the end.)

In [95]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


#3. Arrange X feature matrices
X_test = df_test[features]
y_test = df_test[target]

#impute missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
X_test_imp = imputer.fit_transform(X_test)

log_reg.fit(X_test_imp, y_test)

#convert to DataFrame
#X_test_imp = pd.DataFrame(X_test_imp, columns=X_test.columns)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [91]:
X_test_imp.head()

Yelp    Google  Cost
0  3.833333  3.966667  8.00
1  3.833333  3.966667  7.25
2  4.500000  3.800000  4.19
3  3.500000  4.300000  7.00
4  3.833333  3.966667  8.50

In [97]:
X_test_imp.shape, y_test.shape

((38, 3), (38,))

In [98]:
print("Test Accuracy", log_reg.score(X_test_imputed, y_test))

Test Accuracy 0.47368421052631576


In [100]:
#samething as above
y_pred = log_reg.predict(X_test_imp)
print("Accuracy score", accuracy_score(y_pred, y_test))

Accuracy score 0.47368421052631576


#Commit your notebook to your fork of the GitHub repo.

#Stretch Goals

##Make exploratory visualizations.

##Do one-hot encoding.

##Do feature scaling.

##Get and plot your coefficients.