<a href="https://colab.research.google.com/github/mooglol/DS-Unit-2-Regression-Classification/blob/master/module4/assignment_regression_classification_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science, Unit 2: Predictive Modeling

# Regression & Classification, Module 4


## Assignment

- [ ] Watch Aaron's [video #1](https://www.youtube.com/watch?v=pREaWFli-5I) (12 minutes) & [video #2](https://www.youtube.com/watch?v=bDQgVt4hFgY) (9 minutes) to learn about the mathematics of Logistic Regression.
- [ ] [Sign up for a Kaggle account](https://www.kaggle.com/), if you don’t already have one. Go to our Kaggle InClass competition website. You will be given the URL in Slack. Go to the Rules page. Accept the rules of the competition.
- [ ] Do train/validate/test split with the Tanzania Waterpumps data.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your validation accuracy score.
- [ ] Submit your predictions to our Kaggle competition. (Go to our Kaggle InClass competition webpage. Use the blue **Submit Predictions** button to upload your CSV file. Or you can use the Kaggle API to submit your predictions.)
- [ ] Commit your notebook to your fork of the GitHub repo.

---


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Clean the data. For ideas, refer to [The Quartz guide to bad data](https://github.com/Quartz/bad-data-guide),  a "reference to problems seen in real-world data along with suggestions on how to resolve them." One of the issues is ["Zeros replace missing values."](https://github.com/Quartz/bad-data-guide#zeros-replace-missing-values)
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding. For example, you could try `quantity`, `basin`, `extraction_type_class`, and more. (But remember it may not work with high cardinality categoricals.)
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

---

## Data Dictionary 

### Features

Your goal is to predict the operating condition of a waterpoint for each record in the dataset. You are provided the following set of information about the waterpoints:

- `amount_tsh` : Total static head (amount water available to waterpoint)
- `date_recorded` : The date the row was entered
- `funder` : Who funded the well
- `gps_height` : Altitude of the well
- `installer` : Organization that installed the well
- `longitude` : GPS coordinate
- `latitude` : GPS coordinate
- `wpt_name` : Name of the waterpoint if there is one
- `num_private` :  
- `basin` : Geographic water basin
- `subvillage` : Geographic location
- `region` : Geographic location
- `region_code` : Geographic location (coded)
- `district_code` : Geographic location (coded)
- `lga` : Geographic location
- `ward` : Geographic location
- `population` : Population around the well
- `public_meeting` : True/False
- `recorded_by` : Group entering this row of data
- `scheme_management` : Who operates the waterpoint
- `scheme_name` : Who operates the waterpoint
- `permit` : If the waterpoint is permitted
- `construction_year` : Year the waterpoint was constructed
- `extraction_type` : The kind of extraction the waterpoint uses
- `extraction_type_group` : The kind of extraction the waterpoint uses
- `extraction_type_class` : The kind of extraction the waterpoint uses
- `management` : How the waterpoint is managed
- `management_group` : How the waterpoint is managed
- `payment` : What the water costs
- `payment_type` : What the water costs
- `water_quality` : The quality of the water
- `quality_group` : The quality of the water
- `quantity` : The quantity of water
- `quantity_group` : The quantity of water
- `source` : The source of the water
- `source_type` : The source of the water
- `source_class` : The source of the water
- `waterpoint_type` : The kind of waterpoint
- `waterpoint_type_group` : The kind of waterpoint

### Labels

There are three possible values:

- `functional` : the waterpoint is operational and there are no repairs needed
- `functional needs repair` : the waterpoint is operational, but needs repairs
- `non functional` : the waterpoint is not operational

--- 

## Generate a submission

Your code to generate a submission file may look like this:

```python
# estimator is your model or pipeline, which you've fit on X_train

# X_test is your pandas dataframe or numpy array, 
# with the same number of rows, in the same order, as test_features.csv, 
# and the same number of columns, in the same order, as X_train

y_pred = estimator.predict(X_test)


# Makes a dataframe with two columns, id and status_group, 
# and writes to a csv file, without the index

sample_submission = pd.read_csv('sample_submission.csv')
submission = sample_submission.copy()
submission['status_group'] = y_pred
submission.to_csv('your-submission-filename.csv', index=False)
```

If you're working locally, the csv file is saved in the same directory as your notebook.

If you're using Google Colab, you can use this code to download your submission csv file.

```python
from google.colab import files
files.download('your-submission-filename.csv')
```

---

In [1]:
import os, sys
in_colab = 'google.colab' in sys.modules

# If you're in Colab...
if in_colab:
    # Pull files from Github repo
    os.chdir('/content')
    !git init .
    !git remote add origin https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification.git
    !git pull origin master
    
    # Install required python packages
    !pip install -r requirements.txt
    
    # Change into directory for module
    os.chdir('module4')

Initialized empty Git repository in /content/.git/
remote: Enumerating objects: 156, done.
remote: Total 156 (delta 0), reused 0 (delta 0), pack-reused 156
Receiving objects: 100% (156/156), 19.30 MiB | 7.00 MiB/s, done.
Resolving deltas: 100% (71/71), done.
From https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
     |████████████████████████████████| 92kB 3.5MB/s 
     |████████████████████████████████| 112kB 9.2MB/s 
     |████████████████████████████████| 133kB 45.2MB/s 
     |████████████████████████████████| 57.7MB 1.4MB/s 
     |████████████████████████████████| 235kB 37.2MB/s 
     |████████████████████████████████| 614kB 37.8MB/s 
     |████████████████████████████████| 235kB 37.2MB/s 
     |████████████████████████████████| 307kB 42.2MB/s 
     |████████████████████████████████| 215kB 43.1MB/s 
     |████████████████████████████████| 51kB 21.9MB/s 
     |███████████

In [0]:
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
# Read the Tanzania Waterpumps data
# train_features.csv : the training set features
# train_labels.csv : the training set labels
# test_features.csv : the test set features
# sample_submission.csv : a sample submission file in the correct format
    
import pandas as pd

train_features = pd.read_csv('../data/waterpumps/train_features.csv')
train_labels = pd.read_csv('../data/waterpumps/train_labels.csv')
test_features = pd.read_csv('../data/waterpumps/test_features.csv')
sample_submission = pd.read_csv('../data/waterpumps/sample_submission.csv')

assert train_features.shape == (59400, 40)
assert train_labels.shape == (59400, 2)
assert test_features.shape == (14358, 40)
assert sample_submission.shape == (14358, 2)

In [12]:
train_features.head()

id  amount_tsh  ...              waterpoint_type waterpoint_type_group
0  69572      6000.0  ...           communal standpipe    communal standpipe
1   8776         0.0  ...           communal standpipe    communal standpipe
2  34310        25.0  ...  communal standpipe multiple    communal standpipe
3  67743         0.0  ...  communal standpipe multiple    communal standpipe
4  19728         0.0  ...           communal standpipe    communal standpipe

[5 rows x 40 columns]

In [13]:
train_labels.head()

id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [14]:
train = pd.merge(train_features, train_labels, how='inner', on='id')
train.head()

id  amount_tsh  ... waterpoint_type_group    status_group
0  69572      6000.0  ...    communal standpipe      functional
1   8776         0.0  ...    communal standpipe      functional
2  34310        25.0  ...    communal standpipe      functional
3  67743         0.0  ...    communal standpipe  non functional
4  19728         0.0  ...    communal standpipe      functional

[5 rows x 41 columns]

In [7]:
train.shape

(59400, 41)

In [0]:
status_ranks = {'non functional': 1, 'functional needs repair': 2, 'functional': 3}
train.status_group = train.status_group.map(status_ranks)

In [16]:
train.head()

id  amount_tsh  ... waterpoint_type_group status_group
0  69572      6000.0  ...    communal standpipe            3
1   8776         0.0  ...    communal standpipe            3
2  34310        25.0  ...    communal standpipe            3
3  67743         0.0  ...    communal standpipe            1
4  19728         0.0  ...    communal standpipe            3

[5 rows x 41 columns]

In [17]:
from sklearn.model_selection import train_test_split

my_train, my_val = train_test_split(train, random_state=42)
my_train.shape, my_val.shape

((44550, 41), (14850, 41))

In [18]:
my_train[:5]

id  amount_tsh  ... waterpoint_type_group status_group
24947  33935        20.0  ...    communal standpipe            1
22630  49654         0.0  ...             hand pump            3
13789  39287         0.0  ...             hand pump            3
15697  60510         0.0  ...    communal standpipe            3
22613  24259         0.0  ...    communal standpipe            1

[5 rows x 41 columns]

In [19]:
my_train.describe()

id     amount_tsh  ...  construction_year  status_group
count  44550.000000   44550.000000  ...       44550.000000  44550.000000
mean   37087.547744     326.361114  ...        1303.746083      2.157464
std    21436.367755    3291.640548  ...         950.647840      0.949964
min        0.000000       0.000000  ...           0.000000      1.000000
25%    18555.250000       0.000000  ...           0.000000      1.000000
50%    36992.500000       0.000000  ...        1986.000000      3.000000
75%    55631.500000      20.000000  ...        2004.000000      3.000000
max    74247.000000  350000.000000  ...        2013.000000      3.000000

[8 rows x 11 columns]

In [20]:
target = 'status_group'
y_train = my_train[target]
y_train.value_counts(normalize=True)

3    0.542334
1    0.384871
2    0.072795
Name: status_group, dtype: float64

In [21]:
y_train.mode()[0]

3

In [0]:
majority_class = y_train.mode()[0]
y_pred = [majority_class] * len(y_train)

In [23]:
sum(abs(y_pred - y_train)) / len(y_train) 

0.8425364758698092

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_pred)

0.542334455667789

In [25]:
my_val.describe()

id     amount_tsh  ...  construction_year  status_group
count  14850.000000   14850.000000  ...       14850.000000  14850.000000
mean   37197.883838     291.518195  ...        1291.371650      2.162963
std    21503.842453    1853.797688  ...         954.504635      0.949305
min        3.000000       0.000000  ...           0.000000      1.000000
25%    18459.250000       0.000000  ...           0.000000      1.000000
50%    37244.000000       0.000000  ...        1985.000000      3.000000
75%    55721.250000      25.000000  ...        2004.000000      3.000000
max    74246.000000  138000.000000  ...        2013.000000      3.000000

[8 rows x 11 columns]

In [26]:
y_val = my_val[target]
y_pred = [majority_class] * len(y_val)
accuracy_score(y_pred, y_val)

0.5453198653198653

In [27]:
my_train.describe()

id     amount_tsh  ...  construction_year  status_group
count  44550.000000   44550.000000  ...       44550.000000  44550.000000
mean   37087.547744     326.361114  ...        1303.746083      2.157464
std    21436.367755    3291.640548  ...         950.647840      0.949964
min        0.000000       0.000000  ...           0.000000      1.000000
25%    18555.250000       0.000000  ...           0.000000      1.000000
50%    36992.500000       0.000000  ...        1986.000000      3.000000
75%    55631.500000      20.000000  ...        2004.000000      3.000000
max    74247.000000  350000.000000  ...        2013.000000      3.000000

[8 rows x 11 columns]

In [28]:
# 1. Import estimator class
from sklearn.linear_model import LinearRegression

# 2. Instantiate this class
linear_reg = LinearRegression()

# 3. Arrange X feature matrices (already did y target vectors)
features = ['population', 'construction_year', 'amount_tsh']
X_train = my_train[features]
X_val = my_val[features]

# Impute missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.transform(X_val)

# 4. Fit the model
linear_reg.fit(X_train_imputed, y_train)

# 5. Apply the model to new data.
# The predictions look like this ...
linear_reg.predict(X_val_imputed)

array([2.10080962, 2.10080962, 2.18011818, ..., 2.18331791, 2.10080962,
       2.17955393])

In [29]:
pd.Series(linear_reg.coef_, features)

population           0.000009
construction_year    0.000039
amount_tsh           0.000014
dtype: float64

In [30]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver='lbfgs')
log_reg.fit(X_train_imputed, y_train)
print('Validation Accuracy', log_reg.score(X_val_imputed, y_val))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Validation Accuracy 0.5453198653198653


In [31]:
log_reg.predict(X_val_imputed)

array([3, 3, 3, ..., 3, 3, 3])

In [32]:
log_reg.predict_proba(X_val_imputed)

array([[0.40867579, 0.08896321, 0.502361  ],
       [0.40867579, 0.08896321, 0.502361  ],
       [0.39567172, 0.06338588, 0.5409424 ],
       ...,
       [0.39265677, 0.06512445, 0.54221877],
       [0.40867579, 0.08896321, 0.502361  ],
       [0.3954902 , 0.06428724, 0.54022256]])

In [33]:
log_reg.coef_

array([[-4.86035587e-05, -1.41461830e-05, -3.18210022e-04],
       [ 7.98071802e-05, -1.83544560e-04, -1.43565314e-06],
       [ 1.61270230e-05,  8.42906778e-05,  2.18938201e-04]])

In [34]:
pd.Series(linear_reg.coef_, features)

population           0.000009
construction_year    0.000039
amount_tsh           0.000014
dtype: float64

In [35]:
log_reg.intercept_

array([-3.77395886e-01, -2.33152998e+00,  1.70262715e-07])

In [0]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.e**(-x))

In [0]:
import category_encoders as ce
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegressionCV
from sklearn.preprocessing import StandardScaler

target = 'status_group'
features = ['amount_tsh', 'gps_height', 'installer', 'waterpoint_type', 'source', 'source_type', 'population', 'scheme_management', 'region_code', 'district_code', 'construction_year', 'payment', 'management', 'funder']
X_train = my_train[features]
y_train = my_train[target]
X_val = my_val[features]
y_val = my_val[target]

encoder = ce.OneHotEncoder(use_cat_names=True)
X_train_encoded = encoder.fit_transform(X_train)
X_val_encoded = encoder.transform(X_val)

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)

In [37]:
model = LogisticRegressionCV(cv=5, n_jobs=-1, random_state=42)
model.fit(X_train_scaled, y_train)
model.score(X_val_scaled, y_val)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.6997979797979798

In [38]:
X_test = test_features[features]
X_test_encoded = encoder.transform(X_test)
X_test_imputed = imputer.transform(X_test_encoded)
X_test_scaled = scaler.transform(X_test_imputed)
y_pred = model.predict(X_test_scaled)

print(y_pred)

[1 3 1 ... 1 1 1]


In [39]:
submission = test_features[['id']].copy()
submission['status_group'] = y_pred
submission.describe()

id  status_group
count  14358.000000  14358.000000
mean   37232.859799      2.322399
std    21382.890432      0.945127
min       10.000000      1.000000
25%    18765.500000      1.000000
50%    37442.000000      3.000000
75%    55909.250000      3.000000
max    74249.000000      3.000000

In [40]:
submission.head()

id  status_group
0  50785             1
1  51630             3
2  17168             1
3  45559             1
4  49871             3

In [0]:
submission_ranks = {1: 'non functional', 2: 'functional needs repair', 3: 'functional'}
submission.status_group = submission.status_group.map(submission_ranks)

In [42]:
submission.head()

id    status_group
0  50785  non functional
1  51630      functional
2  17168  non functional
3  45559  non functional
4  49871      functional

In [0]:
submission.to_csv('mugilchoi-submission-02.csv', index=False)

In [0]:
from google.colab import files
files.download('mugilchoi-submission-02.csv')