<a href="https://colab.research.google.com/github/jpiche0720/DS-Unit-2-Linear-Models/blob/master/module1-regression-1/LS_DS_211_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 1*

---

# Regression 1

## Assignment

You'll use another **New York City** real estate dataset. 

But now you'll **predict how much it costs to rent an apartment**, instead of how much it costs to buy a condo.

The data comes from renthop.com, an apartment listing website.

- [X] Look at the data. Choose a feature, and plot its relationship with the target.
- [X] Use scikit-learn for linear regression with one feature. You can follow the [5-step process from Jake VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/05.02-introducing-scikit-learn.html#Basics-of-the-API).
- [X] Define a function to make new predictions and explain the model coefficient.
- [X] Organize and comment your code.

> [Do Not Copy-Paste.](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit) You must type each of these exercises in, manually. If you copy and paste, you might as well not even do them. The point of these exercises is to train your hands, your brain, and your mind in how to read, write, and see code. If you copy-paste, you are cheating yourself out of the effectiveness of the lessons.

If your **Plotly** visualizations aren't working:
- You must have JavaScript enabled in your browser
- You probably want to use Chrome or Firefox
- You may need to turn off ad blockers
- [If you're using Jupyter Lab locally, you need to install some "extensions"](https://plot.ly/python/getting-started/#jupyterlab-support-python-35)

## Stretch Goals
- [ ] Do linear regression with two or more features.
- [ ] Read [The Discovery of Statistical Regression](https://priceonomics.com/the-discovery-of-statistical-regression/)
- [ ] Read [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf), Chapter 2.1: What Is Statistical Learning?

In [0]:
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
# Read New York City apartment rental listing data
import pandas as pd
df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

In [0]:
# Remove outliers: 
# the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= 1375) & (df['price'] <= 15500) & 
        (df['latitude'] >=40.57) & (df['latitude'] < 40.99) &
        (df['longitude'] >= -74.1) & (df['longitude'] <= -73.38)]

# LOOK AT THE DATA
## Interesting Features:

- interest_level(if interest level would create outliers) 
- Bedrooms / Bathrooms (size of unit) 
- doorman (income for security personel)
- new construction 
- dispay address
- lat and long(in relation to attractions,schools,hospitals)
- description (maybe how many words are used in describing may be a way to capture how many features are in that listing)

In [0]:
print(df.shape)
df.head()

(48818, 34)


bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [0]:
df['price'].describe()

count    48818.000000
mean      3579.560982
std       1762.420875
min       1375.000000
25%       2500.000000
50%       3150.000000
75%       4095.000000
max      15500.000000
Name: price, dtype: float64

In [0]:
df['price'].value_counts()


2500     1106
3200      879
3000      837
2700      776
2400      772
         ... 
6939        1
4858        1
10095       1
6811        1
12630       1
Name: price, Length: 2685, dtype: int64

# one feature

In [0]:
model = LinearRegression()
features = ['bedrooms']
target = 'price'

In [0]:
X_train = df[features]
y_train = df[target]
y_pred = model.fit(X_train,y_train)

In [0]:
rooms = 3
X_test = [[rooms]]

model.predict(X_test)

array([4827.73665176])

# Using Sci Kit Learn Linear Regression with one feature against the target
- from sklearn.linear_model import LinearRegression
## Features = Bedrooms + Bathrooms + dining room = Size Rank
## Target = Price

### Use plotly to visualize our single feature against our target 

- import plotly.express as px


In [0]:
from sklearn.linear_model import LinearRegression
import plotly.express as px

In [0]:
df['size_rank'] = df['bathrooms']+df['bedrooms']+df['dining_room']
df['size_rank'].value_counts()

In [0]:
#set model, features, and target 
model = LinearRegression()
features = ['size_rank']
target = 'price'

In [0]:
px.scatter(df,'size_rank',y= 'price',trendline='ols')

In [0]:
#set training data 
# fit model to training data
X_train = df[features]
y_train = df[target]
y_pred = model.fit(X_train,y_train)



In [0]:
# create test senario
rooms = 5
X_test = [[rooms]]

model.predict(X_test)

array([5232.77657623])

# A DIFFERENT FEATURE 
## The length of the description 

- is a longer descrition explaining more features


In [0]:
# get the length of strings and make a new column
def string_length(str):
  return len(str)

string_length('hello')

df['description']= df['description'].astype(str)

In [0]:

df['description_length'] = df['description'].apply(string_length)
df['description_length']
  

0         588
1           8
2         691
3         492
4         479
         ... 
49347     787
49348    1125
49349     671
49350     735
49351     799
Name: description_length, Length: 48818, dtype: int64

In [0]:
px.scatter(df, x= 'description_length',y = 'price',trendline='ols')

In [0]:
features = ['description_length']
target = 'price'

X_train = df[features]
y_train = df[target]
y_pred = model.fit(X_train,y_train)



In [0]:
d_length = 1000
X_test = [[d_length]]

In [0]:
model.predict(X_test)

array([3869.78609261])

# DEFINE A FUNCTION 

- Make new predictions
- explain the model coefficient 

In [0]:
def apartment_price(room_number):
  feature = ['size_rank']
  target = 'price'
  X_train = df[feature]
  y_train = df[target]
  model = LinearRegression()
  model.fit(X_train, y_train)
  X_test = [[room_number]]
  prediction = model.predict(X_test)
  coef = model.coef_
  intercept = model.intercept_
  
  print(f'Our model predicts: $ {prediction[0]:.0f}')
  print(f'The apartment increases in price by: $ {coef.round(2)[0]:.0f}','per room plus')
  print(f'the y intercept: ${intercept:.0f}')
  return 

In [0]:
apartment_price(5)


Our model predicts: $ 5233
The apartment increases in price by: $ 766 per room plus
the y intercept: $1403


In [0]:
(766*5)+ 1403

5233

#Stretch Goals

## Using Description length and room size 

In [0]:
model = LinearRegression()
features = ['size_rank','description_length']
target = 'price'
X_train = df[features]
y_train = df[target]
model.fit(X_train,y_train)
X_test = [[6,2000]]
model.predict(X_test)

array([6344.40160061])